### ISSUE TITLE
bash: /usr/local/bin/fsociety: No such file or directory

### ISSUE THREAD

**Issue by TrixCoder** [fsociety-team/fsociety#109]
pip install fsociety
Defaulting to user installation because normal site-packages is not writeable
Collecting fsociety
  Using cached fsociety-3.2.8-py2.py3-none-any.whl (26 kB)
Requirement already satisfied: rich>=9.2.0 in /home/utkarsh/.local/lib/python3.10/site-packages (from fsociety) (12.6.0)
Requirement already satisfied: distro>=1.7.0 in /usr/lib/python3/dist-packages (from fsociety) (1.7.0)
Requirement already satisfied: requests>=2.23.0 in /usr/lib/python3/dist-packages (from fsociety) (2.25.1)
Requirement already satisfied: GitPython>=3.1.3 in /home/utkarsh/.local/lib/python3.10/site-packages (from fsociety) (3.1.29)
Requirement already satisfied: gitdb<5,>=4.0.1 in /home/utkarsh/.local/lib/python3.10/site-packages (from GitPython>=3.1.3->fsociety) (4.0.9)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /home/utkarsh/.local/lib/python3.10/site-packages (from rich>=9.2.0->fsociety) (0.9.1)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /home/utkarsh/.local/lib/python3.10/site-packages (from rich>=9.2.0->fsociety) (2.13.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /home/utkarsh/.local/lib/python3.10/site-packages (from gitdb<5,>=4.0.1->GitPython>=3.1.3->fsociety) (5.0.0)
Installing collected packages: fsociety
Successfully installed fsociety-3.2.8

**Comment by thehappydinoa** [comment]
Try running `python -m fsociety`.

**Comment by TrixCoder** [comment]
Yep it works now, Thanks
