### ISSUE TITLE
DOCKER IMAGE FSOCIETY ARGUMENT NOT RECOGNIZED

### ISSUE THREAD

**Issue by Raffaele-Doti** [fsociety-team/fsociety#153]
I downloaded the latest image of FSociety as .readme suggests but the "fsociety" argument seems to not be recognized from the docker image.

PRE-REQUISITES : 

* A Windows host with a fully working docker installation
* A correctly pulled docker image obtained after running the "docker pull fsocietyteam/fsociety" command 

STEPS TO REPRODUCE : 
 
* Run the "docker run -it fsocietyteam/fsociety fsociety" command

WHAT I WAS EXPECTING TO GET : 

I was expecting the FSociety startup menu in an interactive docker container shell

WHAT THE COMMAND RETURNS :

usage: fsociety [-h] [-i] [-s]
fsociety: error: unrecognized arguments: fsociety

WINDOWS TERMINAL SCREENSHOT : 

![image](https://user-images.githubusercontent.com/27352611/220198103-a36f73d1-ac08-47ba-84d5-c3cf1f00b0c0.png)

**Comment by thehappydinoa** [comment]
Hey just try it without the last fsociety, I will update the docs too.
