### ISSUE TITLE
AttributeError: module 'os' has no attribute 'uname'

### ISSUE THREAD

**Issue by sylar003** [fsociety-team/fsociety#190]
**Which Tool?**
Error message when I input fsociety

**What is the error?**
Stacktrace:
AttributeError: module 'os' has no attribute 'uname'
```bash
```
![image](https://github.com/fsociety-team/fsociety/assets/126435040/33bfe862-9000-484a-85e5-61c2114ecdd6)

**fsociety info**
Run `fsociety --info` in your terminal and copy the results here.

```bash
```

**Comment by TobiTenno** [comment]
Oooof, this is probably on me. Looks like uname is probably not on windows. Are you on windows?

**Comment by TobiTenno** [comment]
Oooof, this is probably on me. Looks like uname is probably not on windows. Are you on windows?

Come to think of it, I dunno how to avoid this, cause your python is reacting to it even existing
... I'll have to see if nesting it in an outer check for windows works

**Comment by TobiTenno** [comment]
fix proposed ^

**Comment by thehappydinoa** [comment]
Thanks for doing this.
