### ISSUE TITLE
Install works, command doesn't..

### ISSUE THREAD

**Issue by Vrodo** [fsociety-team/fsociety#213]
![image](https://github.com/fsociety-team/fsociety/assets/66423440/b75a2437-3004-4fb4-8f3c-4dd700373321)

Followed this tutorial: https://www.youtube.com/watch?v=2ldY_9zJYRQ

**Comment by thehappydinoa** [comment]
This is an environmental issue on your part. Here is an article that will help you add your Python bin directory to your PATH: <https://realpython.com/add-python-to-path/>
