### ISSUE TITLE
Fsociety doesn't work on Windows with Python 3.12

### ISSUE THREAD

**Issue by RealJosephKnapp** [fsociety-team/fsociety#243]
**Which Tool?**
I cannot load the tools.

**What is the error?**
Microsoft Windows [Version 10.0.22631.3672]
(c) Microsoft Corporation. All rights reserved.

C:\Users\*******>fsociety
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in _run_module_as_main:198                                                                       │
│ in _run_code:88                                                                                  │
│                                                                                                  │
│ in <module>:4                                                                                    │
│                                                                                                  │
│ C:\Program Files\Python312\Lib\site-packages\fsociety\__main__.py:14 in <module>                 │
│                                                                                                  │
│    11 import fsociety.information_gathering                                                      │
│    12 import fsociety.networking                                                                 │
│    13 import fsociety.obfuscation                                                                │
│ ❱  14 import fsociety.passwords                                                                  │
│    15 import fsociety.web_apps                                                                   │
│    16 from fsociety.console import console                                                       │
│    17 from fsociety.core.config import CONFIG_FILE, get_config, write_config                     │
│                                                                                                  │
│ C:\Program Files\Python312\Lib\site-packages\fsociety\passwords\__init__.py:1 in <module>        │
│                                                                                                  │
│ ❱ 1 from .cli import __tools__, cli                                                              │
│   2                                                                                              │
│   3 __all__ = ["cli", "__tools__"] + [str(tool) for tool in __tools__]                           │
│   4                                                                                              │
│                                                                                                  │
│ C:\Program Files\Python312\Lib\site-packages\fsociety\passwords\cli.py:8 in <module>             │
│                                                                                                  │
│    5 from .cr3dov3r import cr3dov3r                                                              │
│    6 from .cupp import cupp                                                                      │
│    7 from .hash_buster import hash_buster                                                        │
│ ❱  8 from .traitor import traitor                                                                │
│    9                                                                                             │
│   10 __tools__ = [cupp, cr3dov3r, hash_buster, changeme, traitor]                                │
│   11                                                                                             │
│                                                                                                  │
│ C:\Program Files\Python312\Lib\site-packages\fsociety\passwords\traitor.py:56 in <module>        │
│                                                                                                  │
│   53 │   │   return self.run()                                                                   │
│   54                                                                                             │
│   55                                                                                             │
│ ❱ 56 traitor = TraitorRepo()                                                                     │
│   57                                                                                             │
│                                                                                                  │
│ C:\Program Files\Python312\Lib\site-packages\fsociety\passwords\traitor.py:13 in __init__        │
│                                                                                                  │
│   10                                                                                             │
│   11 class TraitorRepo(GitHubRepo):                                                              │
│   12 │   def __init__(self):                                                                     │
│ ❱ 13 │   │   if os.uname().machine in arch_map:                                                  │
│   14 │   │   │   self.arch = arch_map.get(os.uname().machine)                                    │
│   15 │   │   else:                                                                               │
│   16 │   │   │   self.arch = ""                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: module 'os' has no attribute 'uname'

C:\Users\******>

```bash
```

**fsociety info**
Run `fsociety --info` in your terminal and copy the results here.
"""
C:\Users\*******>fsociety --info
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in _run_module_as_main:198                                                                       │
│ in _run_code:88                                                                                  │
│                                                                                                  │
│ in <module>:4                                                                                    │
│                                                                                                  │
│ C:\Program Files\Python312\Lib\site-packages\fsociety\__main__.py:14 in <module>                 │
│                                                                                                  │
│    11 import fsociety.information_gathering                                                      │
│    12 import fsociety.networking                                                                 │
│    13 import fsociety.obfuscation                                                                │
│ ❱  14 import fsociety.passwords                                                                  │
│    15 import fsociety.web_apps                                                                   │
│    16 from fsociety.console import console                                                       │
│    17 from fsociety.core.config import CONFIG_FILE, get_config, write_config                     │
│                                                                                                  │
│ C:\Program Files\Python312\Lib\site-packages\fsociety\passwords\__init__.py:1 in <module>        │
│                                                                                                  │
│ ❱ 1 from .cli import __tools__, cli                                                              │
│   2                                                                                              │
│   3 __all__ = ["cli", "__tools__"] + [str(tool) for tool in __tools__]                           │
│   4                                                                                              │
│                                                                                                  │
│ C:\Program Files\Python312\Lib\site-packages\fsociety\passwords\cli.py:8 in <module>             │
│                                                                                                  │
│    5 from .cr3dov3r import cr3dov3r                                                              │
│    6 from .cupp import cupp                                                                      │
│    7 from .hash_buster import hash_buster                                                        │
│ ❱  8 from .traitor import traitor                                                                │
│    9                                                                                             │
│   10 __tools__ = [cupp, cr3dov3r, hash_buster, changeme, traitor]                                │
│   11                                                                                             │
│                                                                                                  │
│ C:\Program Files\Python312\Lib\site-packages\fsociety\passwords\traitor.py:56 in <module>        │
│                                                                                                  │
│   53 │   │   return self.run()                                                                   │
│   54                                                                                             │
│   55                                                                                             │
│ ❱ 56 traitor = TraitorRepo()                                                                     │
│   57                                                                                             │
│                                                                                                  │
│ C:\Program Files\Python312\Lib\site-packages\fsociety\passwords\traitor.py:13 in __init__        │
│                                                                                                  │
│   10                                                                                             │
│   11 class TraitorRepo(GitHubRepo):                                                              │
│   12 │   def __init__(self):                                                                     │
│ ❱ 13 │   │   if os.uname().machine in arch_map:                                                  │
│   14 │   │   │   self.arch = arch_map.get(os.uname().machine)                                    │
│   15 │   │   else:                                                                               │
│   16 │   │   │   self.arch = ""                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: module 'os' has no attribute 'uname'

C:\Users\******>
"""

```bash
```
I installed fsociety through pip with admin privilidges. I am using complete python 3.12.3 and precompiled standard library with the python visual C++ debugging available, but I do not have MSVC installed.

**Comment by TobiTenno** [comment]
if i remember right, we found a while back that windows python doesn't expose uname, which seems to be the issue here. i'm trying it out on my branch, but it'll take a bit to get to my branch on windows, so please be patient :heart_hands:

**Comment by thehappydinoa** [comment]
Fixed in #247

**Comment by TobiTenno** [comment]
I don't think this is fixed in #247, @thehappydinoa, it's still failing for me on a fresh install, unless the latest publish didn't go out?
