### ISSUE TITLE
TaWP

### ISSUE THREAD

**Issue by tomrichard3011** [fsociety-team/fsociety#4]
**Link to Tool**
https://github.com/tomrichard3011/TaWP

**Why?**
I was inspired to create this tool from a scene in Mr. Robot. You may remember when Elliot uses a social engineering attack to get some personal information on someone and create a word list for that specific person.
My tool does the same kind of thing. I understand my tool isn't very useful, but I thought I should submit it since both my tool and your framework have the same source of inspiration.
Thank you for your time.

P.S. If you have any suggestions or comments for my tool, feel free to let me know.

**Comment by Atiqlaa** [comment]
Hii
