### ISSUE TITLE
sherlock bug? I've updated as well

### ISSUE THREAD

**Issue by PrometheusPy** [fsociety-team/fsociety#59]
sherlock gives this error:
'python3' is not recognized as an internal or external command,
operable program or batch file.
sherlock returned a non-zero exit code
Do you want to reinstall? (y/n):

fsoc info: 
version = 3.2.6
agreement = true
ssh_clone = false
os = windows
host_file = hosts.txt
usernames_file = usernames.txt

# Python Version
3.9.5

# Windows
10

**Comment by thehappydinoa** [comment]
Hi there,

At the moment fsociety only supports *-nix environments. I would suggest using the docker instructions if you are on Windows. 

Thank you
