### ISSUE TITLE
Stand alone

### ISSUE THREAD

**Issue by philsoma41** [fsociety-team/fsociety#8]
Attempting to install fsociety onto a stand alone network that has no internet connectivity. Have downloaded all files on the GitHub, and attempted to modify the install.sh to install fsociety and it fails out. Any help welcome!!

**Comment by thehappydinoa** [comment]
Hi there,

This package is for automating the use of other GitHub projects, at the moment this project will not work in an air gapped environment. I would gladly accept a PR for this, to learn more see our [Contribution Guidelines](https://github.com/fsociety-team/fsociety/blob/master/.github/CONTRIBUTING.md).
